### ISSUE TITLE
stormpath-rails fails

### ISSUE THREAD

**Issue by leoamigood** [stormpath/stormpath-rails#72]
have .bash_profile configured
Have similar issue to https://github.com/stormpath/stormpath-rails/issues/61

```
/usr/local/bundle/gems/stormpath-sdk-1.4.0/lib/stormpath-sdk/http/authc/sauthc1_signer.rb:88:in `+': no implicit conversion of nil into String (TypeError)
	from /usr/local/bundle/gems/stormpath-sdk-1.4.0/lib/stormpath-sdk/http/authc/sauthc1_signer.rb:88:in `sign_request'
	from /usr/local/bundle/gems/stormpath-sdk-1.4.0/lib/stormpath-sdk/http/http_client_request_executor.rb:32:in `execute_request'
	from /usr/local/bundle/gems/stormpath-sdk-1.4.0/lib/stormpath-sdk/data_store.rb:145:in `execute_request'
	from /usr/local/bundle/gems/stormpath-sdk-1.4.0/lib/stormpath-sdk/data_store.rb:57:in `get_resource'
	from /usr/local/bundle/gems/stormpath-sdk-1.4.0/lib/stormpath-sdk/resource/associations.rb:68:in `get'
	from /usr/local/bundle/gems/stormpath-sdk-1.4.0/lib/stormpath-sdk/client.rb:39:in `tenant'
	from /usr/local/bundle/gems/stormpath-sdk-1.4.0/lib/stormpath-sdk/resource/associations.rb:43:in `block in has_many'
	from /usr/local/bundle/gems/stormpath-rails-2.3.0/lib/stormpath/rails/config/application_resolution.rb:41:in `client_applications'
	from /usr/local/bundle/gems/stormpath-rails-2.3.0/lib/stormpath/rails/config/application_resolution.rb:37:in `client_has_exactly_two_applications?'
	from /usr/local/bundle/gems/stormpath-rails-2.3.0/lib/stormpath/rails/config/application_resolution.rb:29:in `automatic_resolution'
	from /usr/local/bundle/gems/stormpath-rails-2.3.0/lib/stormpath/rails/config/application_resolution.rb:22:in `app'
	from /usr/local/bundle/gems/stormpath-rails-2.3.0/lib/stormpath/rails/config/dynamic_configuration.rb:26:in `app'
	from /usr/local/bundle/gems/stormpath-rails-2.3.0/lib/stormpath/rails/config/dynamic_configuration.rb:67:in `proccess_account_store_verification'
	from /usr/local/bundle/gems/stormpath-rails-2.3.0/lib/stormpath/rails/config/dynamic_configuration.rb:19:in `initialize'
	from /usr/local/bundle/gems/stormpath-rails-2.3.0/lib/stormpath/rails/configuration.rb:24:in `new'
	from /usr/local/bundle/gems/stormpath-rails-2.3.0/lib/stormpath/rails/configuration.rb:24:in `block in config_object'
	from /usr/local/bundle/gems/stormpath-rails-2.3.0/lib/stormpath/rails/configuration.rb:23:in `tap'
	from /usr/local/bundle/gems/stormpath-rails-2.3.0/lib/stormpath/rails/configuration.rb:23:in `config_object'
	from /usr/local/bundle/gems/stormpath-rails-2.3.0/lib/stormpath/rails/configuration.rb:19:in `web'
	from /usr/local/bundle/gems/stormpath-rails-2.3.0/lib/stormpath/rails/router.rb:31:in `block in stormpath_rails_routes'
	from /usr/local/bundle/gems/actionpack-4.2.5/lib/action_dispatch/routing/mapper.rb:941:in `block in constraints'
	from /usr/local/bundle/gems/actionpack-4.2.5/lib/action_dispatch/routing/mapper.rb:817:in `scope'
	from /usr/local/bundle/gems/actionpack-4.2.5/lib/action_dispatch/routing/mapper.rb:941:in `constraints'
	from /usr/local/bundle/gems/stormpath-rails-2.3.0/lib/stormpath/rails/router.rb:30:in `stormpath_rails_routes'
	from /u/apps/bullsandcows/config/routes.rb:58:in `block in <top (required)>'
	from /usr/local/bundle/gems/actionpack-4.2.5/lib/action_dispatch/routing/route_set.rb:434:in `instance_exec'
	from /usr/local/bundle/gems/actionpack-4.2.5/lib/action_dispatch/routing/route_set.rb:434:in `eval_block'
	from /usr/local/bundle/gems/actionpack-4.2.5/lib/action_dispatch/routing/route_set.rb:412:in `draw'
	from /u/apps/bullsandcows/config/routes.rb:1:in `<top (required)>'
	from /usr/local/bundle/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `load'
	from /usr/local/bundle/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `block in load'
	from /usr/local/bundle/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /usr/local/bundle/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `load'
	from /usr/local/bundle/gems/railties-4.2.5/lib/rails/application/routes_reloader.rb:40:in `block in load_paths'
	from /usr/local/bundle/gems/railties-4.2.5/lib/rails/application/routes_reloader.rb:40:in `each'
	from /usr/local/bundle/gems/railties-4.2.5/lib/rails/application/routes_reloader.rb:40:in `load_paths'
	from /usr/local/bundle/gems/railties-4.2.5/lib/rails/application/routes_reloader.rb:16:in `reload!'
	from /usr/local/bundle/gems/railties-4.2.5/lib/rails/application/routes_reloader.rb:26:in `block in updater'
	from /usr/local/bundle/gems/activesupport-4.2.5/lib/active_support/file_update_checker.rb:75:in `execute'
	from /usr/local/bundle/gems/railties-4.2.5/lib/rails/application/routes_reloader.rb:27:in `updater'
	from /usr/local/bundle/gems/railties-4.2.5/lib/rails/application/routes_reloader.rb:7:in `execute_if_updated'
	from /usr/local/bundle/gems/railties-4.2.5/lib/rails/application/finisher.rb:69:in `block in <module:Finisher>'
	from /usr/local/bundle/gems/railties-4.2.5/lib/rails/initializable.rb:30:in `instance_exec'
	from /usr/local/bundle/gems/railties-4.2.5/lib/rails/initializable.rb:30:in `run'
	from /usr/local/bundle/gems/railties-4.2.5/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /usr/local/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
	from /usr/local/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /usr/local/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /usr/local/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /usr/local/lib/ruby/2.3.0/tsort.rb:347:in `each'
	from /usr/local/lib/ruby/2.3.0/tsort.rb:347:in `call'
	from /usr/local/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
	from /usr/local/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
	from /usr/local/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
	from /usr/local/bundle/gems/railties-4.2.5/lib/rails/initializable.rb:54:in `run_initializers'
	from /usr/local/bundle/gems/railties-4.2.5/lib/rails/application.rb:352:in `initialize!'
	from /u/apps/bullsandcows/config/environment.rb:5:in `<top (required)>'
	from /usr/local/bundle/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
	from /usr/local/bundle/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `block in require'
	from /usr/local/bundle/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /usr/local/bundle/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
	from /usr/local/bundle/gems/spring-1.7.1/lib/spring/application.rb:92:in `preload'
	from /usr/local/bundle/gems/spring-1.7.1/lib/spring/application.rb:143:in `serve'
	from /usr/local/bundle/gems/spring-1.7.1/lib/spring/application.rb:131:in `block in run'
	from /usr/local/bundle/gems/spring-1.7.1/lib/spring/application.rb:125:in `loop'
	from /usr/local/bundle/gems/spring-1.7.1/lib/spring/application.rb:125:in `run'
	from /usr/local/bundle/gems/spring-1.7.1/lib/spring/application/boot.rb:19:in `<top (required)>'
	from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'
```

**Comment by cilim** [comment]
@leoamigood please answer a couple of questions so we can fix your problem quicker.
1. What version of the gem are you using?
2. Paste your environment variables (don't need to paste the actual value)
3. Paste your stormpath.yml configuration file

**Comment by leoamigood** [comment]
1. What version of the gem are you using?
2.3.0

2. Paste your environment variables
> env | grep STORM | cut -d= -f1
```STORMPATH_CLIENT_APIKEY_ID
STORMPATH_CLIENT_APIKEY_SECRET
STORMPATH_APPLICATION_HREF```

3. Paste your stormpath.yml configuration file
```stormpath:
  application:
    href: <%= ENV['STORMPATH_APPLICATION_HREF'] %>
    name: null

  web:
    basePath: null

    oauth2:
      enabled: true
      uri: "/oauth/token"
      client_credentials:
        enabled: true
        accessToken:
          ttl: 3600 # seconds
      password:
        enabled: true
        validationStrategy: "local"

    accessTokenCookie:
      name: "access_token"
      httpOnly: true

      # See cookie-authentication.md for explanation of
      # how `null` values behave for these properties.
      secure: null
      path: null
      domain: null

    refreshTokenCookie:
      name: "refresh_token"
      httpOnly: true

      # See cookie-authentication.md for explanation of
      # how `null` values behave for these properties.
      secure: null
      path: null
      domain: null

    # By default the Stormpath integration will respond to JSON and HTML
    # requests.  If a requested type is not in this list, the Stormpath
    # integration should pass on the request, and allow the developer or base
    # framework to handle the response.
    #
    # If the request does not specify an Accept header, or the preferred content
    # type is */*, the Stormpath integration will respond with the first type in
    # this list.
    produces:
      - application/json
      - text/html

    register:
      enabled: true
      uri: "/register"
      nextUri: "/"
      autoLogin: false
      form:
        fields:
          givenName:
            enabled: true
            visible: true
            label: "First Name"
            placeholder: "First Name"
            required: true
            type: "text"
          middleName:
            enabled: false
            visible: true
            label: "Middle Name"
            placeholder: "Middle Name"
            required: true
            type: "text"
          surname:
            enabled: true
            visible: true
            label: "Last Name"
            placeholder: "Last Name"
            required: true
            type: "text"
          username:
            enabled: false
            visible: true
            label: "Username"
            placeholder: "Username"
            required: true
            type: "text"
          email:
            enabled: true
            visible: true
            label: "Email"
            placeholder: "Email"
            required: true
            type: "email"
          password:
            enabled: true
            visible: true
            label: "Password"
            placeholder: "Password"
            required: true
            type: "password"
          confirmPassword:
            enabled: false
            visible: true
            label: "Confirm Password"
            placeholder: "Confirm Password"
            required: true
            type: "password"
        fieldOrder:
          - "username"
          - "givenName"
          - "middleName"
          - "surname"
          - "email"
          - "password"
          - "confirmPassword"
      view: "stormpath/rails/register/new"

    # Unless verifyEmail.enabled is specifically set to false, the email
    # verification feature must be automatically enabled if the default account
    # store for the defined Stormpath application has the email verification
    # workflow enabled.
    verifyEmail:
      enabled: null
      uri: "/verify"
      nextUri: "/login?status=verified"
      view: "stormpath/rails/verify_email/new"

    login:
      enabled: true
      uri: "/login"
      nextUri: "/"
      view: "stormpath/rails/login/new"
      form:
        fields:
          login:
            enabled: true
            visible: true
            label: "Username or Email"
            placeholder: "Username or Email"
            required: true
            type: "text"
          password:
            enabled: true
            visible: true
            label: "Password"
            placeholder: "Password"
            required: true
            type: "password"
        fieldOrder:
          - "login"
          - "password"

    logout:
      enabled: true
      uri: "/logout"
      nextUri: "/"

    # Unless forgotPassword.enabled is explicitly set to false, this feature
    # will be automatically enabled if the default account store for the defined
    # Stormpath application has the password reset workflow enabled.
    forgotPassword:
      enabled: null
      uri: "/forgot"
      view: "stormpath/rails/forgot_password/new"
      nextUri: "/login?status=forgot"

    # Unless changePassword.enabled is explicitly set to false, this feature
    # will be automatically enabled if the default account store for the defined
    # Stormpath application has the password reset workflow enabled.
    changePassword:
      enabled: null
      autoLogin: false
      uri: "/change"
      nextUri: "/login?status=reset"
      view: "stormpath/rails/change_password/new"
      errorUri: "/forgot?status=invalid_sptoken"

    # If idSite.enabled is true, the user should be redirected to ID site for
    # login, registration, and password reset.  They should also be redirected
    # through ID Site on logout.
    idSite:
      enabled: false
      loginUri: ""
      forgotUri: "/#/forgot"
      registerUri: "/#/register"

    # A callback so Stormpath can pass information to the web application. This is
    # currently being used for ID Site, but may be used in the future for SAML,
    # Stormpath handled social login, webhooks, and other messages from Stormpath.
    callback:
      enabled: true
      uri: "/stormpathCallback"

    # Social login configuration.  This defines the callback URIs for OAuth
    # flows, and the scope that is requested of each provider.  Some providers
    # want space-separated scopes, some want comma-separated.  As such, these
    # string values should be passed directly, as defined.
    #
    # These settings have no affect if the application does not have an account
    # store for the given provider.
    social:
      facebook:
        uri: "/callbacks/facebook"
        scope: "email"
      github:
        uri: "/callbacks/github"
        scope: "user:email"
      google:
        uri: "/callbacks/google"
        scope: "email profile"
      linkedin:
        uri: "/callbacks/linkedin"
        scope: "r_basicprofile r_emailaddress"

    # The /me route is for front-end applications, it returns a JSON object with
    # the current user object.  The developer can opt-in to expanding account
    # resources on this enpdoint.
    me:
      enabled: true
      uri: "/me"
      expand:
        apiKeys: false
        applications: false
        customData: false
        directory: false
        groupMemberships: false
        groups: false
        providerData: false
        tenant: false```

**Comment by cilim** [comment]
@leoamigood please update your version to `2.3.1` and let us know if that fixed it for you.

**Comment by leoamigood** [comment]
Yes, it's fixed! Thank you for a quick turnaround!

**Comment by cilim** [comment]
Thank you for reporting the problem!
Sorry if it caused any inconvenience
