### ISSUE TITLE
Getting started Q 

### ISSUE THREAD

**Issue by mdeggies** [stormpath/stormpath-rails#77]
Hey Marko, 

Super noobie question for you. I followed part of this guide to create a rails project: http://guides.rubyonrails.org/getting_started.html

I'm now trying to integrate Stormpath into the project. I added ``gem 'stormpath-rails', '~> 2.5.0'`` below the other gems in the Gemfile, added Stormpath to ``routes.rb``: 

```
Rails.application.routes.draw do
  get 'welcome/index'
  root 'welcome#index'
  stormpath_rails_routes
end
```

I'm running with ``bundle install`` and then ``bin/rails server``. 

This is the error I'm getting (note -- I don't get this error when I remove stormpath_rails_routes from the routes.rb file -- did I miss a step somewhere?): 

```
λ bin/rails server
=> Booting Puma
=> Rails 5.0.1 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
Cookie#domain returns dot-less domain name now. Use Cookie#dot_domain if you need "." at the beginning.
Exiting
/Users/mdegges/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/json/common.rb:156:in `parse': 822: unexpected token at '<!doctype html> (MultiJson::ParseError)

<html>
<head>
    <title>Login</title>

    <meta charset="utf-8" />
    <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
    <meta http-equiv="Cache-Control" content="no-cache" />
    <!-- prevent leaking sensitive information across -->
    <meta name="Referrer" content="origin-when-crossorigin" />
    <script type="text/javascript">
        // -------------------------------------------- CONSOLE PROOFING
        (function () {
          if (!window.console) {
            window.console = {};
            window.console.stack = [];
            window.console.log = function (val) {
              window.console.stack.push(val);
            }
          }
        })();
    </script>
    <link rel="icon" type="image/vnd.microsoft.icon" href="/assets/images/favicon.ico" />
    <link rel="stylesheet" href="/assets/styles/fc6d6dc4.main.css" />
    <link href="https://assets.zendesk.com/external/zenbox/v2.6/zenbox.css" rel="stylesheet" type="text/css" />
    <link rel="stylesheet/less" href="/assets/styles/application.less" />
    <script type="text/javascript" src="/assets/js/9cbb3d68.vendor.js"></script>
    <!-- jQuery plugins, jquery is already provided by the vendor bundle -->
    <script type="text/javascript" src="/assets/js/jquery/jquery.cookie.js"></script>
    <script type="text/javascript" src="/assets/js/jquery/jquery.validate.min.js"></script>
    <!-- other scripts -->
    <script type="text/javascript" src="https://assets.zendesk.com/external/zenbox/v2.6/zenbox.js"></script>
    <script type="text/javascript" src="//cdn.optimizely.com/js/225847041.js"></script>

    <!-- LESS.JS -->

    <script type="text/javascript" src="/assets/js/less-1.3.0.min.js"></script>

    <!-- "frame-breaker" to prevent clickjacking in legacy browsers -->
    <style id="preventCJ">body{display:none !important;}</style>

    <!-- refreshing the login page, if the user is idle for a while-->
    <meta http-equiv="refresh" content="1800" />
</head>
<body id="wrapper" class="boundary login">


    <div class="header">
      <div class="container">
        <a class="" href="https://www.stormpath.com">
          <img src="/assets/images/logo_nav.png" id="logoimg" />
        </a>
      </div>
    </div>

    <div id="content" class="loginbody content-column">
        <section>
            <h3 class="text-center">Login</h3>
            <div class="contentpanel details">

                <form id="loginForm" method="post" action="/login">





                    <div class="form-group">
                        <label for="tenantNameKey">
                            <span>Tenant</span>
                            <span>&nbsp;</span>
                            <i class="glyphicon glyphicon-question-sign" data-toggle="tooltip" data-placement="right" title="The name of the tenant to login to. A tenant is a private partition within Stormpath containing all data and settings. If you forgot your Tenant Name, use the &#39;Forgot Tenant?&#39; link below."></i>
                            <a href="/forgotTenant">Forgot Tenant?</a>
                        </label>
                        <input id="tenantNameKey" path="tenantNameKey" type="text" class="form-control" tabindex="1" name="tenantNameKey" value="" />
                    </div>
                    <div class="form-group">
                        <label for="email">Email</label>
                        <input id="email" path="email" class="form-control" tabindex="2" type="text" name="email" value="" />
                    </div>
                    <div class="form-group">
                        <label for="password">
                            <span>Password</span>
                            <a href="/forgotLogin">Forgot Password?</a>
                        </label>
                        <input id="password" path="password" class="form-control" tabindex="3" autocomplete="off" type="password" name="password" value="" />
                        <input name="csrfToken" type="hidden" value="cWpQUmhoM1ZGTDYwbmthaDZIMG5LalVKRks0YklBKy9tMzFFVXVLbll5dz06MTQ4NDI0Mzc2MjU1ODpXUU9iNmQ2bHNXRTcvVk91S09McENYOW5zL2RzZlZZNklKZVNpYXdkWlBZPQ==" />
                        <input name="hpvalue" type="hidden" value="" />
                    </div>
                    <input name="state" type="hidden" id="state" value="eyJhbGciOiJIUzI1NiJ9.eyJyZXF1ZXN0ZWRVcmwiOiIvdGVuYW50cy9jdXJyZW50In0.4jaiFDbKj46CHyqpv3TX7TFR_SpDMsKkvAYJ1O9eD6s" />
                    <button type="submit" id="loginbutton" class="btn btn-primary actionbutton large" tabindex="4">Log In</button>
                </form>

            </div>
        </section>

        <br />
        <div class="content-column">
            <div class="contentpanel text-center">
                <span>Don't have an account? <a href="/register">Sign Up for Stormpath</a></span>
            </div>
        </div>
    </div>


    <script type="text/javascript">
        // <![CDATA[
        var _kmk = _kmk || '684b854336bd3a6523260ebd991eec06b18b929a';
        function _kms(u) {
            setTimeout(function () {
                var d = document, f = d.getElementsByTagName('script')[0],
                        s = d.createElement('script');
                s.type = 'text/javascript';
                s.async = true;
                s.src = u;
                f.parentNode.insertBefore(s, f);
            }, 1);
        }
        _kms('//i.kissmetrics.com/i.js');
        _kms('//doug1izaerwt3.cloudfront.net/' + _kmk + '.1.js');

        function submitMarketing() {
            if ((typeof _kmq !== 'undefined') && (!window.location.host.match(/localhost/))) {
                _kmq.push(['set', {'email': $('#email').val()}]);
                _kmq.push(['record', 'Login Submitted', {'email': $('#email').val()}]);
                _kmq.push(['identify', $('#email').val()]);
            }
        }

        $('#emailMessage, #passwordMessage').hide();
        $(document).ready(function () {

            function submitHandler(form) {
                submitMarketing();
                setTimeout(function (argument) {
                    form.submit();
                },100);
            }

            $('#email').focus();
            var loginForm = $('#loginForm');
            loginForm.validate({
                debug: false,
                errorElement: "div",
                rules: {
                    tenantNameKey: {required: true},
                    email: {
                        required: true,
                        email: true
                    },
                    password: {required: true}
                },
                submitHandler: submitHandler
            });


        });


        // ]]>

    </script>

<script type="text/javascript">
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
                (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-29159574-1', 'auto');
    ga('send', 'pageview');
</script>
<!-- "frame-breaker" to prevent clickjacking in legacy browsers -->
<script type="text/javascript">
    if (self === top) {
        var preventClickjack = document.getElementById("preventCJ");
        preventClickjack.parentNode.removeChild(preventClickjack);
    } else {
        top.location = self.location;
    }
</script>
<script>/*<![CDATA[*/window.zEmbed||function(e,t){var n,o,d,i,s,a=[],r=document.createElement("iframe");window.zEmbed=function(){a.push(arguments)},window.zE=window.zE||window.zEmbed,r.src="javascript:false",r.title="",r.role="presentation",(r.frameElement||r).style.cssText="display: none",d=document.getElementsByTagName("script"),d=d[d.length-1],d.parentNode.insertBefore(r,d),i=r.contentWindow,s=i.document;try{o=s}catch(c){n=document.domain,r.src='javascript:var d=document.open();d.domain="'+n+'";void(0);',o=s}o.open()._l=function(){var o=this.createElement("script");n&&(this.domain=n),o.id="js-iframe-async",o.src=e,this.t=+new Date,this.zendeskHost=t,this.zEQueue=a,this.body.appendChild(o)},o.write('<body onload="document._l();">'),o.close()}("https://assets.zendesk.com/embeddable_framework/main.js","stormpath.zendesk.com");/*]]>*/</script>
<script type="text/javascript">
    (function(d,s,i,r) {
        if (d.getElementById(i)){return;}
        var n=d.createElement(s),e=d.getElementsByTagName(s)[0];
        n.id=i;n.src='//js.hs-analytics.net/analytics/'+(Math.ceil(new Date()/r)*r)+'/475298.js';
        e.parentNode.insertBefore(n, e);
    })(document,"script","hs-analytics",300000);
</script>
<script src="//cdn.optimizely.com/js/225847041.js"></script>
<script type="text/javascript">
    (function() {
        window._pa = window._pa || {};
        // _pa.orderId = "";
        // _pa.revenue = "";
        var pa = document.createElement('script'); pa.type = 'text/javascript'; pa.async = true;
        pa.src = ('https:' == document.location.protocol ? 'https:' : 'http:') + "//tag.perfectaudience.com/serve/51fc2c6f1b440adfcc000099.js";
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(pa, s);
    })();
    // $('[data-toggle="tooltip"]').tooltip();
    $(function () {
      $('[data-toggle="tooltip"]').tooltip()
    })
</script>


<!-- Trialfire Start -->
    <script src="//cdn.trialfire.com/tf.js"></script>
    <script>Trialfire.init('d579cc60-b5da-4472-96a8-e1f60fe440e1');</script>
<!-- Trialfire End -->

</body>
</html>'
	from /Users/mdegges/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/json/common.rb:156:in `parse'
	from /Users/mdegges/.rvm/gems/ruby-2.3.0/gems/multi_json-1.12.1/lib/multi_json/adapters/json_common.rb:14:in `load'
	from /Users/mdegges/.rvm/gems/ruby-2.3.0/gems/multi_json-1.12.1/lib/multi_json/adapter.rb:21:in `load'
	from /Users/mdegges/.rvm/gems/ruby-2.3.0/gems/multi_json-1.12.1/lib/multi_json.rb:122:in `load'
	from /Users/mdegges/.rvm/gems/ruby-2.3.0/gems/stormpath-sdk-1.4.0/lib/stormpath-sdk/data_store.rb:147:in `execute_request'
	from /Users/mdegges/.rvm/gems/ruby-2.3.0/gems/stormpath-sdk-1.4.0/lib/stormpath-sdk/data_store.rb:57:in `get_resource'
	from /Users/mdegges/.rvm/gems/ruby-2.3.0/gems/stormpath-sdk-1.4.0/lib/stormpath-sdk/resource/associations.rb:68:in `get'
	from /Users/mdegges/.rvm/gems/ruby-2.3.0/gems/stormpath-sdk-1.4.0/lib/stormpath-sdk/client.rb:39:in `tenant'
	from /Users/mdegges/.rvm/gems/ruby-2.3.0/gems/stormpath-sdk-1.4.0/lib/stormpath-sdk/resource/associations.rb:43:in `block in has_many'
	from /Users/mdegges/.rvm/gems/ruby-2.3.0/gems/stormpath-rails-2.5.0/lib/stormpath/rails/config/application_resolution.rb:47:in `app_from_href'
	from /Users/mdegges/.rvm/gems/ruby-2.3.0/gems/stormpath-rails-2.5.0/lib/stormpath/rails/config/application_resolution.rb:18:in `app'
	from /Users/mdegges/.rvm/gems/ruby-2.3.0/gems/stormpath-rails-2.5.0/lib/stormpath/rails/config/dynamic_configuration.rb:27:in `app'
	from /Users/mdegges/.rvm/gems/ruby-2.3.0/gems/stormpath-rails-2.5.0/lib/stormpath/rails/config/dynamic_configuration.rb:68:in `proccess_account_store_verification'
	from /Users/mdegges/.rvm/gems/ruby-2.3.0/gems/stormpath-rails-2.5.0/lib/stormpath/rails/config/dynamic_configuration.rb:19:in `initialize'
	from /Users/mdegges/.rvm/gems/ruby-2.3.0/gems/stormpath-rails-2.5.0/lib/stormpath/rails/configuration.rb:24:in `new'
	from /Users/mdegges/.rvm/gems/ruby-2.3.0/gems/stormpath-rails-2.5.0/lib/stormpath/rails/configuration.rb:24:in `block in config_object'
	from /Users/mdegges/.rvm/gems/ruby-2.3.0/gems/stormpath-rails-2.5.0/lib/stormpath/rails/configuration.rb:23:in `tap'
	from /Users/mdegges/.rvm/gems/ruby-2.3.0/gems/stormpath-rails-2.5.0/lib/stormpath/rails/configuration.rb:23:in `config_object'
	from /Users/mdegges/.rvm/gems/ruby-2.3.0/gems/stormpath-rails-2.5.0/lib/stormpath/rails/configuration.rb:19:in `web'
	from /Users/mdegges/.rvm/gems/ruby-2.3.0/gems/stormpath-rails-2.5.0/lib/stormpath/rails/router.rb:31:in `block in stormpath_rails_routes'
	from /Users/mdegges/.rvm/gems/ruby-2.3.0/gems/actionpack-5.0.1/lib/action_dispatch/routing/mapper.rb:993:in `block in constraints'
	from /Users/mdegges/.rvm/gems/ruby-2.3.0/gems/actionpack-5.0.1/lib/action_dispatch/routing/mapper.rb:855:in `scope'
	from /Users/mdegges/.rvm/gems/ruby-2.3.0/gems/actionpack-5.0.1/lib/action_dispatch/routing/mapper.rb:993:in `constraints'
	from /Users/mdegges/.rvm/gems/ruby-2.3.0/gems/stormpath-rails-2.5.0/lib/stormpath/rails/router.rb:30:in `stormpath_rails_routes'
	from /Users/mdegges/Desktop/Stormpath/stormpath-rails/stormpath-rails/config/routes.rb:4:in `block in <top (required)>'
	from /Users/mdegges/.rvm/gems/ruby-2.3.0/gems/actionpack-5.0.1/lib/action_dispatch/routing/route_set.rb:389:in `instance_exec'
	from /Users/mdegges/.rvm/gems/ruby-2.3.0/gems/actionpack-5.0.1/lib/action_dispatch/routing/route_set.rb:389:in `eval_block'
	from /Users/mdegges/.rvm/gems/ruby-2.3.0/gems/actionpack-5.0.1/lib/action_dispatch/routing/route_set.rb:371:in `draw'
	from /Users/mdegges/Desktop/Stormpath/stormpath-rails/stormpath-rails/config/routes.rb:1:in `<top (required)>'
	from /Users/mdegges/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:287:in `load'
	from /Users/mdegges/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:287:in `block in load'
	from /Users/mdegges/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /Users/mdegges/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:287:in `load'
	from /Users/mdegges/.rvm/gems/ruby-2.3.0/gems/railties-5.0.1/lib/rails/application/routes_reloader.rb:40:in `block in load_paths'
	from /Users/mdegges/.rvm/gems/ruby-2.3.0/gems/railties-5.0.1/lib/rails/application/routes_reloader.rb:40:in `each'
	from /Users/mdegges/.rvm/gems/ruby-2.3.0/gems/railties-5.0.1/lib/rails/application/routes_reloader.rb:40:in `load_paths'
	from /Users/mdegges/.rvm/gems/ruby-2.3.0/gems/railties-5.0.1/lib/rails/application/routes_reloader.rb:16:in `reload!'
	from /Users/mdegges/.rvm/gems/ruby-2.3.0/gems/railties-5.0.1/lib/rails/application/routes_reloader.rb:26:in `block in updater'
	from /Users/mdegges/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.1/lib/active_support/file_update_checker.rb:77:in `execute'
	from /Users/mdegges/.rvm/gems/ruby-2.3.0/gems/railties-5.0.1/lib/rails/application/routes_reloader.rb:27:in `updater'
	from /Users/mdegges/.rvm/gems/ruby-2.3.0/gems/railties-5.0.1/lib/rails/application/routes_reloader.rb:7:in `execute_if_updated'
	from /Users/mdegges/.rvm/gems/ruby-2.3.0/gems/railties-5.0.1/lib/rails/application/finisher.rb:119:in `block in <module:Finisher>'
	from /Users/mdegges/.rvm/gems/ruby-2.3.0/gems/railties-5.0.1/lib/rails/initializable.rb:30:in `instance_exec'
	from /Users/mdegges/.rvm/gems/ruby-2.3.0/gems/railties-5.0.1/lib/rails/initializable.rb:30:in `run'
	from /Users/mdegges/.rvm/gems/ruby-2.3.0/gems/railties-5.0.1/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /Users/mdegges/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
	from /Users/mdegges/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /Users/mdegges/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /Users/mdegges/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /Users/mdegges/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:347:in `each'
	from /Users/mdegges/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:347:in `call'
	from /Users/mdegges/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
	from /Users/mdegges/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
	from /Users/mdegges/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
	from /Users/mdegges/.rvm/gems/ruby-2.3.0/gems/railties-5.0.1/lib/rails/initializable.rb:54:in `run_initializers'
	from /Users/mdegges/.rvm/gems/ruby-2.3.0/gems/railties-5.0.1/lib/rails/application.rb:352:in `initialize!'
	from /Users/mdegges/Desktop/Stormpath/stormpath-rails/stormpath-rails/config/environment.rb:5:in `<top (required)>'
	from /Users/mdegges/Desktop/Stormpath/stormpath-rails/stormpath-rails/config.ru:3:in `require_relative'
	from /Users/mdegges/Desktop/Stormpath/stormpath-rails/stormpath-rails/config.ru:3:in `block in <main>'
	from /Users/mdegges/.rvm/gems/ruby-2.3.0/gems/rack-2.0.1/lib/rack/builder.rb:55:in `instance_eval'
	from /Users/mdegges/.rvm/gems/ruby-2.3.0/gems/rack-2.0.1/lib/rack/builder.rb:55:in `initialize'
	from /Users/mdegges/Desktop/Stormpath/stormpath-rails/stormpath-rails/config.ru:in `new'
	from /Users/mdegges/Desktop/Stormpath/stormpath-rails/stormpath-rails/config.ru:in `<main>'
	from /Users/mdegges/.rvm/gems/ruby-2.3.0/gems/rack-2.0.1/lib/rack/builder.rb:49:in `eval'
	from /Users/mdegges/.rvm/gems/ruby-2.3.0/gems/rack-2.0.1/lib/rack/builder.rb:49:in `new_from_string'
	from /Users/mdegges/.rvm/gems/ruby-2.3.0/gems/rack-2.0.1/lib/rack/builder.rb:40:in `parse_file'
	from /Users/mdegges/.rvm/gems/ruby-2.3.0/gems/rack-2.0.1/lib/rack/server.rb:318:in `build_app_and_options_from_config'
	from /Users/mdegges/.rvm/gems/ruby-2.3.0/gems/rack-2.0.1/lib/rack/server.rb:218:in `app'
	from /Users/mdegges/.rvm/gems/ruby-2.3.0/gems/railties-5.0.1/lib/rails/commands/server.rb:59:in `app'
	from /Users/mdegges/.rvm/gems/ruby-2.3.0/gems/rack-2.0.1/lib/rack/server.rb:353:in `wrapped_app'
	from /Users/mdegges/.rvm/gems/ruby-2.3.0/gems/railties-5.0.1/lib/rails/commands/server.rb:124:in `log_to_stdout'
	from /Users/mdegges/.rvm/gems/ruby-2.3.0/gems/railties-5.0.1/lib/rails/commands/server.rb:77:in `start'
	from /Users/mdegges/.rvm/gems/ruby-2.3.0/gems/railties-5.0.1/lib/rails/commands/commands_tasks.rb:90:in `block in server'
	from /Users/mdegges/.rvm/gems/ruby-2.3.0/gems/railties-5.0.1/lib/rails/commands/commands_tasks.rb:85:in `tap'
	from /Users/mdegges/.rvm/gems/ruby-2.3.0/gems/railties-5.0.1/lib/rails/commands/commands_tasks.rb:85:in `server'
	from /Users/mdegges/.rvm/gems/ruby-2.3.0/gems/railties-5.0.1/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /Users/mdegges/.rvm/gems/ruby-2.3.0/gems/railties-5.0.1/lib/rails/commands.rb:18:in `<top (required)>'
	from /Users/mdegges/Desktop/Stormpath/stormpath-rails/stormpath-rails/bin/rails:9:in `require'
	from /Users/mdegges/Desktop/Stormpath/stormpath-rails/stormpath-rails/bin/rails:9:in `<top (required)>'
	from /Users/mdegges/.rvm/gems/ruby-2.3.0/gems/spring-2.0.0/lib/spring/client/rails.rb:28:in `load'
	from /Users/mdegges/.rvm/gems/ruby-2.3.0/gems/spring-2.0.0/lib/spring/client/rails.rb:28:in `call'
	from /Users/mdegges/.rvm/gems/ruby-2.3.0/gems/spring-2.0.0/lib/spring/client/command.rb:7:in `call'
	from /Users/mdegges/.rvm/gems/ruby-2.3.0/gems/spring-2.0.0/lib/spring/client.rb:30:in `run'
	from /Users/mdegges/.rvm/gems/ruby-2.3.0/gems/spring-2.0.0/bin/spring:49:in `<top (required)>'
	from /Users/mdegges/.rvm/gems/ruby-2.3.0/gems/spring-2.0.0/lib/spring/binstub.rb:31:in `load'
	from /Users/mdegges/.rvm/gems/ruby-2.3.0/gems/spring-2.0.0/lib/spring/binstub.rb:31:in `<top (required)>'
	from /Users/mdegges/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Users/mdegges/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Users/mdegges/Desktop/Stormpath/stormpath-rails/stormpath-rails/bin/spring:14:in `<top (required)>'
	from bin/rails:3:in `load'
	from bin/rails:3:in `<main>')
```

**Comment by cilim** [comment]
Hi Michele,

after running `bundle install` run the generator to insert the config yaml file and the neccessary controller module: `rails generate stormpath:install`

Also, make sure you exported your environment variables to your .bashrc (or .zshrc):

```
export STORMPATH_CLIENT_APIKEY_ID=_your_key_
export STORMPATH_CLIENT_APIKEY_SECRET=_your_secret_
export STORMPATH_APPLICATION_HREF=https://api.stormpath.com/v1/applications/app_id
```

Lastly, go to `config/stormpath.yml` in your Rails application and place your Stormpath application URL in the configuration file like this:

```
stormpath:
  application:
    href: <%= ENV['STORMPATH_APPLICATION_HREF'] %>
```

**Comment by mdeggies** [comment]
Thanks Marko!!! This worked for me.
